# Propaedic procedures
propaedeutic_procedure = Medical::Procedure.find_or_create_by(name: "Propaedeutic")
propaedeutic_procedure.children.find_or_create_by(name: "Auscultation")
propaedeutic_procedure.children.find_or_create_by(name: "Medical inspection")
propaedeutic_procedure.children.find_or_create_by(name: "Palpation")
propaedeutic_procedure.children.find_or_create_by(name: "Percussion")
propaedeutic_procedure.children.find_or_create_by(name: "Vital signs")

# Surgical procedures
surgical_procedure = Medical::Procedure.find_or_create_by(name: "Surgical")
surgical_procedure.children.find_or_create_by(name: "Ablation")
surgical_procedure.children.find_or_create_by(name: "Amputation")
surgical_procedure.children.find_or_create_by(name: "Biopsy")
surgical_procedure.children.find_or_create_by(name: "Cardiopulmonary resuscitation")
surgical_procedure.children.find_or_create_by(name: "Cryosurgery")
surgical_procedure.children.find_or_create_by(name: "Endoscopic surgery")
surgical_procedure.children.find_or_create_by(name: "Facial rejuvenation")
surgical_procedure.children.find_or_create_by(name: "General surgery")
surgical_procedure.children.find_or_create_by(name: "Hand surgery")
surgical_procedure.children.find_or_create_by(name: "Hemilaminectomy")
surgical_procedure.children.find_or_create_by(name: "Image-guided surgery")
surgical_procedure.children.find_or_create_by(name: "Knee cartilage replacement therapy")
surgical_procedure.children.find_or_create_by(name: "Laminectomy")
surgical_procedure.children.find_or_create_by(name: "Laparoscopic surgery")
surgical_procedure.children.find_or_create_by(name: "Lithotomy")
surgical_procedure.children.find_or_create_by(name: "Lithotriptor")
surgical_procedure.children.find_or_create_by(name: "Lobotomy")
surgical_procedure.children.find_or_create_by(name: "Neovaginoplasty")
surgical_procedure.children.find_or_create_by(name: "Radiosurgery")
surgical_procedure.children.find_or_create_by(name: "Stereotactic surgery")
surgical_procedure.children.find_or_create_by(name: "Vaginoplasty")
surgical_procedure.children.find_or_create_by(name: "Xenotransplantation")

# Anesthesia procedures
anesthesia_procedure = Medical::Procedure.find_or_create_by(name: "Anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "Dissociative anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "General anesthesia")
local_anesthesia = anesthesia_procedure.children.find_or_create_by(name: "Local anesthesia")
local_anesthesia.children.find_or_create_by(name: "Topical anesthesia")
local_anesthesia.children.find_or_create_by(name: "Epidural")
local_anesthesia.children.find_or_create_by(name: "Spinal anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "Regional anesthesia")


