# Propaedic procedures
propaedeutic_procedure = Medical::Procedure.find_or_create_by(name: "Propaedeutic")
propaedeutic_procedure.children.find_or_create_by(name: "Auscultation")
propaedeutic_procedure.children.find_or_create_by(name: "Medical inspection")
propaedeutic_procedure.children.find_or_create_by(name: "Palpation")
propaedeutic_procedure.children.find_or_create_by(name: "Percussion")
propaedeutic_procedure.children.find_or_create_by(name: "Vital signs")

# Surgical procedures
surgical_procedure = Medical::Procedure.find_or_create_by(name: "Surgical")
surgical_procedure.children.find_or_create_by(name: "Ablation")
surgical_procedure.children.find_or_create_by(name: "Amputation")
surgical_procedure.children.find_or_create_by(name: "Biopsy")
surgical_procedure.children.find_or_create_by(name: "Cardiopulmonary resuscitation")
surgical_procedure.children.find_or_create_by(name: "Cryosurgery")
surgical_procedure.children.find_or_create_by(name: "Endoscopic surgery")
surgical_procedure.children.find_or_create_by(name: "Facial rejuvenation")
surgical_procedure.children.find_or_create_by(name: "General surgery")
surgical_procedure.children.find_or_create_by(name: "Hand surgery")
surgical_procedure.children.find_or_create_by(name: "Hemilaminectomy")
surgical_procedure.children.find_or_create_by(name: "Image-guided surgery")
surgical_procedure.children.find_or_create_by(name: "Knee cartilage replacement therapy")
surgical_procedure.children.find_or_create_by(name: "Laminectomy")
surgical_procedure.children.find_or_create_by(name: "Laparoscopic surgery")
surgical_procedure.children.find_or_create_by(name: "Lithotomy")
surgical_procedure.children.find_or_create_by(name: "Lithotriptor")
surgical_procedure.children.find_or_create_by(name: "Lobotomy")
surgical_procedure.children.find_or_create_by(name: "Neovaginoplasty")
surgical_procedure.children.find_or_create_by(name: "Radiosurgery")
surgical_procedure.children.find_or_create_by(name: "Stereotactic surgery")
surgical_procedure.children.find_or_create_by(name: "Vaginoplasty")
surgical_procedure.children.find_or_create_by(name: "Xenotransplantation")

# Anesthesia procedures
anesthesia_procedure = Medical::Procedure.find_or_create_by(name: "Anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "Dissociative anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "General anesthesia")
local_anesthesia = anesthesia_procedure.children.find_or_create_by(name: "Local anesthesia")
local_anesthesia.children.find_or_create_by(name: "Topical anesthesia")
local_anesthesia.children.find_or_create_by(name: "Epidural")
local_anesthesia.children.find_or_create_by(name: "Spinal anesthesia")
anesthesia_procedure.children.find_or_create_by(name: "Regional anesthesia")

# Therapeutic

therapeutic_procedure = Medical::Procedure.find_or_create_by(name: "Therapeutic")
therapeutic_procedure.children.find_or_create_by(name: "Thrombosis prophylaxis")
therapeutic_procedure.children.find_or_create_by(name: "Precordial thump")
therapeutic_procedure.children.find_or_create_by(name: "Politzerization")
therapeutic_procedure.children.find_or_create_by(name: "Hemodialysis")
therapeutic_procedure.children.find_or_create_by(name: "Hemofiltration")
therapeutic_procedure.children.find_or_create_by(name: "Plasmapheresis")
therapeutic_procedure.children.find_or_create_by(name: "Apheresis")
therapeutic_procedure.children.find_or_create_by(name: "Extracorporeal membrane oxygenation")
therapeutic_procedure.children.find_or_create_by(name: "Cancer immunotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Cancer vaccine")
therapeutic_procedure.children.find_or_create_by(name: "Cervical conization")
therapeutic_procedure.children.find_or_create_by(name: "Chemotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Cytoluminescent therapy")
therapeutic_procedure.children.find_or_create_by(name: "Insulin potentiation therapy")
therapeutic_procedure.children.find_or_create_by(name: "Low-dose chemotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Monoclonal antibody therapy")
therapeutic_procedure.children.find_or_create_by(name: "Photodynamic therapy")
therapeutic_procedure.children.find_or_create_by(name: "Radiation therapy")
therapeutic_procedure.children.find_or_create_by(name: "Targeted therapy")
therapeutic_procedure.children.find_or_create_by(name: "Tracheal intubation")
therapeutic_procedure.children.find_or_create_by(name: "Unsealed source radiotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Virtual reality therapy")
therapeutic_procedure.children.find_or_create_by(name: "Physical therapy/Physiotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Speech therapy")
therapeutic_procedure.children.find_or_create_by(name: "Phototerapy")
therapeutic_procedure.children.find_or_create_by(name: "Hydrotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Heat therapy")
shock_therapy = therapeutic_procedure.children.find_or_create_by(name: "Shock therapy")
shock_therapy.children.find_or_create_by(name: "Electroconvulsive therapy")
shock_therapy.children.find_or_create_by(name: "Insulin shock therapy")
shock_therapy.children.find_or_create_by(name: "Symptomatic treatment")
therapeutic_procedure.children.find_or_create_by(name: "Fluid replacement therapy")
therapeutic_procedure.children.find_or_create_by(name: "Palliative care")
therapeutic_procedure.children.find_or_create_by(name: "Hyperbaric oxygen therapy")
therapeutic_procedure.children.find_or_create_by(name: "Oxygen therapy")
therapeutic_procedure.children.find_or_create_by(name: "Gene therapy")
therapeutic_procedure.children.find_or_create_by(name: "Enzyme replacement therapy")
therapeutic_procedure.children.find_or_create_by(name: "Vaccination")
therapeutic_procedure.children.find_or_create_by(name: "Intravenous therapy")
therapeutic_procedure.children.find_or_create_by(name: "Phage therapy")
therapeutic_procedure.children.find_or_create_by(name: "Respiratory therapy")
therapeutic_procedure.children.find_or_create_by(name: "Vision therapy")
therapeutic_procedure.children.find_or_create_by(name: "Electrotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Transcutaneous electrical nerve stimulation")
therapeutic_procedure.children.find_or_create_by(name: "Laser therapy")
therapeutic_procedure.children.find_or_create_by(name: "Combination therapy")
therapeutic_procedure.children.find_or_create_by(name: "Occupational therapy")
therapeutic_procedure.children.find_or_create_by(name: "Immunization")
therapeutic_procedure.children.find_or_create_by(name: "Immunosuppressive therapy")
therapeutic_procedure.children.find_or_create_by(name: "Psychotherapy")
therapeutic_procedure.children.find_or_create_by(name: "Drug therapy")
therapeutic_procedure.children.find_or_create_by(name: "Acupuncture")
therapeutic_procedure.children.find_or_create_by(name: "Antivenom")
therapeutic_procedure.children.find_or_create_by(name: "Magnetic therapy")
therapeutic_procedure.children.find_or_create_by(name: "Craniosacral therapy")
therapeutic_procedure.children.find_or_create_by(name: "Chelation therapy")
therapeutic_procedure.children.find_or_create_by(name: "Hormonal therapy")
therapeutic_procedure.children.find_or_create_by(name: "Hormone replacement therapy")
therapeutic_procedure.children.find_or_create_by(name: "Opiate replacement therapy")
therapeutic_procedure.children.find_or_create_by(name: "Cell therapy")
therapeutic_procedure.children.find_or_create_by(name: "Stem cell treatments")
therapeutic_procedure.children.find_or_create_by(name: "Intubation")
therapeutic_procedure.children.find_or_create_by(name: "Nebulization")
therapeutic_procedure.children.find_or_create_by(name: "Inhalation therapy")
therapeutic_procedure.children.find_or_create_by(name: "Particle therapy")
therapeutic_procedure.children.find_or_create_by(name: "Proton therapy")
therapeutic_procedure.children.find_or_create_by(name: "Fluoride therapy")
therapeutic_procedure.children.find_or_create_by(name: "Cold compression therapy")
therapeutic_procedure.children.find_or_create_by(name: "Animal-Assisted Therapy")
therapeutic_procedure.children.find_or_create_by(name: "Negative Pressure Wound Therapy")
therapeutic_procedure.children.find_or_create_by(name: "Nicotine replacement therapy")
therapeutic_procedure.children.find_or_create_by(name: "Oral rehydration therapy")

# Diagnostic
diagnostic_procedure = Medical::Procedure.find_or_create_by(name: "Diagnostic")
lab = diagnostic_procedure.children.find_or_create_by(name: "Lab tests")
lab.children.find_or_create_by(name: "Biopsy test")
lab.children.find_or_create_by(name: "Blood test")
lab.children.find_or_create_by(name: "Stool test")
lab.children.find_or_create_by(name: "Urinalysis")
diagnostic_procedure.children.find_or_create_by(name: "Cardiac stress test")
diagnostic_procedure.children.find_or_create_by(name: "Electrocardiography")
diagnostic_procedure.children.find_or_create_by(name: "Electrocorticography")
diagnostic_procedure.children.find_or_create_by(name: "Electroencephalography")
diagnostic_procedure.children.find_or_create_by(name: "Electromyography")
diagnostic_procedure.children.find_or_create_by(name: "Electroneuronography")
diagnostic_procedure.children.find_or_create_by(name: "Electronystagmography")
diagnostic_procedure.children.find_or_create_by(name: "Electrooculography")
diagnostic_procedure.children.find_or_create_by(name: "Electroretinography")
diagnostic_procedure.children.find_or_create_by(name: "Endoluminal capsule monitoring")
endoscopy = diagnostic_procedure.children.find_or_create_by(name: "Endoscopy")
endoscopy.children.find_or_create_by(name: "Colonoscopy")
endoscopy.children.find_or_create_by(name: "Colposcopy")
endoscopy.children.find_or_create_by(name: "Cystoscopy")
endoscopy.children.find_or_create_by(name: "Gastroscopy")
endoscopy.children.find_or_create_by(name: "Laparoscopy")
endoscopy.children.find_or_create_by(name: "Laryngoscopy")
endoscopy.children.find_or_create_by(name: "Ophthalmoscopy")
endoscopy.children.find_or_create_by(name: "Otoscopy")
endoscopy.children.find_or_create_by(name: "Sigmoidoscopy")
diagnostic_procedure.children.find_or_create_by(name: "Esophageal motility study")
diagnostic_procedure.children.find_or_create_by(name: "Evoked potential")
diagnostic_procedure.children.find_or_create_by(name: "Magnetoencephalography")
imaging = diagnostic_procedure.children.find_or_create_by(name: "Medical imaging")
imaging.children.find_or_create_by(name: "Fluoroscopy")




